version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nexsoll_admin_db
    restart: always
    environment:
      POSTGRES_USER: nexsoll
      POSTGRES_PASSWORD: nexsoll123
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
